name: linting & test coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_LATEST: 20.x
  CI: true

defaults:
  run:
    shell: bash

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
          - 20.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install & build
        run: npm install
      - name: cache eslint for ${{matrix.node-version}}@${{matrix.platform}} (run on one platform only)
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-eslint-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-eslint-
        if: matrix.platform == 'ubuntu-latest' && matrix.node-version == env.NODE_LATEST
      - name: lint (run on one platform only)
        if: matrix.platform == 'ubuntu-latest' && matrix.node-version == env.NODE_LATEST
        run: npm run lint
      - name: test + coverage
        run: npm run test:cover

  check-windows:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{env.NODE_LATEST}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{env.NODE_LATEST}}@${{matrix.platform}}-build-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_LATEST}}
      - name: install & build
        run: npm install
      - name: test
        run: npm run test:cover
